name: tedawi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

########################################################################################
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  # Responsive UI
  flutter_screenutil: 5.9.0
  # Svg support
  flutter_svg: 2.0.10+1
  # Splash screen
  flutter_native_splash: ^2.3.13
  # State Management
  flutter_bloc: ^8.1.4
  # Network
  dio: ^5.4.1
  # error handling
  dartz: ^0.10.1
  # For API calls representation
  pretty_dio_logger: ^1.3.1

  # Dependency Injection
  #get_it 7.6.7

  # Json to dart
  #json_serializable 6.7.1
  #json_annotation 4.8.1

  # Localizations
  # Provides internationalization and localization facilities
  #intl 0.19.0
  #easy_localization 3.0.5

########################################################################################
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

########################################################################################
flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/svgs/

########################################################################################
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
